events {}
http {
  upstream raw_servers { server raw-1:3101; server raw-2:3101; }
  upstream sdk_servers { server sdk-1:3102; server sdk-2:3102; }
  server {
    listen 80;
    access_log off;
    location /raw/ { proxy_pass http://raw_servers; proxy_buffering off; }
    location /sdk/ { proxy_pass http://sdk_servers; proxy_buffering off; }
  }
}
